GET http://localhost:3000/users 
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjc4Nzg0NDgzLCJleHAiOjE2Nzg3ODQ1MTN9.C4ZniajY8YB09tdTRHFGWR3tcHhfOP1w9AnASUuvAvI


###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:3000/api/auth/logout

###
POST http://localhost:3000/api/auth/refresh

###
POST http://localhost:3000/api/auth/register
content-type: application/json

{
    "username": "uerr",
    "password": "uerr"
}

###
GET http://localhost:3000/api/products/dtdd/iphone-14-pro-max


###
POST http://localhost:3000/api/admin/products
content-type: application/json

{
  "href": "iphone-11-pro-max-n123ew-new",
  "brand": "iphone",
  "name": "iPhone 14 Pro Max-New",
  "category": "dtdd",
  "image": "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-max-vang-thumb-600x600.jpg",
  "feature": "6.7\"*and*Super Retina XDR*and*",
  "old_price": 34490000,
  "cur_price": 29490000,
  "product_label": null,
  "intallment": null,
  "label": "GIẢM THÊM 1 TRIỆU",
  "gift": null,
  "pre_order": false,
  "quantity": 10
}



###
POST http://localhost:3000/api/image/
content-type: application/json

{
  "name": "nokia-535.jpg",
  "path": "image-path"
}